### ISSUE TITLE
缺少数据库文件啊，大佬，补一下啊

### ISSUE THREAD

**Issue by shenfanwen** [hollefaye/faye_shop#1]
系统不错，我想本地搭起来看看效果

**Comment by faye-ch** [comment]
谢谢提醒，发给你了。这个项目部署起来可能有点麻烦，麻烦帮我点个赞，谢谢。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hollefaye/faye_shop"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月21日(星期一) 晚上6:33
收件人:&nbsp;"hollefaye/faye_shop"<faye_shop@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[hollefaye/faye_shop] 缺少数据库文件啊，大佬，补一下啊 (#1)





 
系统不错，我想本地搭起来看看效果

**Comment by shenfanwen** [comment]
嗯，已点赞，已关注
